### ISSUE TITLE
Unknown issue with the layout container,

### ISSUE THREAD

**Issue by nielsnl68** [cronvel/terminal-kit#168]
Hello i'm playing around with your interactive document system.

And i modified it a bit To get a header and footer and a mid section.

After doing that i get the following error

```
node:buffer:352
    throw new ERR_INVALID_ARG_VALUE.RangeError('size', size);
    ^

RangeError [ERR_INVALID_ARG_VALUE]: The argument 'size' is invalid. Received -1160
    at Function.allocUnsafe (node:buffer:374:3)
    at new ScreenBuffer (/home/pi/node_projects/nowtalk/node_modules/terminal-kit/lib/ScreenBuffer.js:67:23)
    at new Container (/home/pi/node_projects/nowtalk/node_modules/terminal-kit/lib/document/Container.js:79:18)
    at Layout.computeBoundingBoxes_ (/home/pi/node_projects/nowtalk/node_modules/terminal-kit/lib/document/Layout.js:213:20)
    at Layout.computeBoundingBoxes_ (/home/pi/node_projects/nowtalk/node_modules/terminal-kit/lib/document/Layout.js:168:9)
    at Layout.computeBoundingBoxes_ (/home/pi/node_projects/nowtalk/node_modules/terminal-kit/lib/document/Layout.js:185:9)
    at Layout.computeBoundingBoxes (/home/pi/node_projects/nowtalk/node_modules/terminal-kit/lib/document/Layout.js:107:7)
    at new Layout (/home/pi/node_projects/nowtalk/node_modules/terminal-kit/lib/document/Layout.js:62:7)
    at Object.<anonymous> (/home/pi/node_projects/nowtalk/test.js:32:14)
    at Module._compile (node:internal/modules/cjs/loader:1109:14) {
  code: 'ERR_INVALID_ARG_VALUE'
}
```

And this is the code i use:
```
var layout = new termkit.Layout( {
	parent: document ,
	boxChars: 'double' ,
	layout: {
		id: 'main' ,
		y: 0 , x: 0,
		widthPercent: 100 ,
    heightPercent: 100 ,
		rows: [
			{
				id: 'headerRow' ,
				height: 1 ,
				columns: [ { id: 'header'}	]
			} ,
			{
				id: 'worksheet' ,
				heightPercent: 100 ,
				columns: [
					{ id: 'users' } ,
					{ id: 'message' , widthPercent: 100/3 } 
				]
			} ,
			{
				id: 'footerRow' ,
			  height: 1 ,
				columns: [
					{ id: 'footer' 
          } ,
				]
			}
		]
	}
} ) ;
```

I hope you can help me. I understand it is all still under development so no worries about that.

**Comment by cronvel** [comment]
@nielsnl68 Thanks for reporting, I will try to fix that soon.

Aside from the crash bug, you have two errors on your end:
* on the middle row, you have to remove the `heighPercent: 100`, you can't have 100% of the parent container's height because you obviously have two more rows, by removing the height constraint it will simply use all remaining space
* the header and footer should have a height of at least 3, because of the borders are actually parts of the height (similar to outer width/height in CSS). I admit it's probably not ideal, but at the moment `Layout` has a lot of rough edges.

By fixing this, your code will be able to run.

**Comment by nielsnl68** [comment]
Dont worry about the rough edges, i can live with that atm. As long you pick them up as you did above, and when needed i could help out as well. When you have specific requests. 
That i did something wrong i was sure about it. because it worked before i made the changes, i only could not understand where it did go wrong. 

About the height and width thing.. I indeed expected it to be the inner space without the border, because when do you count them. I mean when you have a table 20x16  with 3 fixed rows. In your setup the top and bottom height are both 3. and the middle one should then set to be 12.  To me the height/width of a row/column is the inner space the borders are extra. More because when you later decide not to use the borders. the design needs to be all changed as well.

About the positioning system would you interesting to extend it? I have a suggestion:

Positive values are as it is now counting from the top left of the container where the widget is inside.
a negative value counts from the opposite side back to the left.
Adding a widget object in the will use the position/size of the linked widget to calculate the position or size.
and 0 (zero) means auto calculated based of the content inside. Only valid for width or x and height or y.
For percentages you could use "19%" af value.

Some examples:
>> widget name {x, y, width, heigth} <<
a.  widgeta {1,1,-1,1}  => means the widgetA will be shown on top from fully left to right (like widthpercentage=100)
b. widgetb {1.-1.-1,-1}  => same as above but now it shows at the bottom.
c. widgetc {1, widgeta, 20, widgetb} => This will automatically between widgeta and widgetb at the left side of the screen.
d. widgetd{-1,  widgeta, 20, widgetb} => the same as above but now it is shown at the right side.
e. widgete{widgetc,widgeta,widgetd,widgerb} => this will use the inner space.
f. An other header could be for example:
   1. headertitle {1,1, 0 ,1} 
   2. rowmenu { headertitle,1,clock,1}
   3. clock {-1,1,10,1 }

When you like the idea, i could create a PR for it, I dont think it is to much work.

**Comment by cronvel** [comment]
@nielsnl68 I think it's better that the userland code explicitly set the correct coordinate, using the parent width and height. The goal is not to re-create a full blown CSS implementation ^^

For the border thing, for instance there are shared, that's why you need to add +2. Still not sure if this was intended.

**Comment by nielsnl68** [comment]
The idea of the above suggestion is to allow a better Responsive terminal layout.
I know it looks overwhelming. But it is just one relative small function that could be called to get the absolute coordinates. And from what i have seen it does exist already. 

But that said it is your call and project. no hard feelings.
