### ISSUE TITLE
Shift+Tab not recognized on windows (powershell 7)

### ISSUE THREAD

**Issue by KevinLee3627** [cronvel/terminal-kit#184]
I noticed in the [key event documentation](https://github.com/cronvel/terminal-kit/blob/master/doc/events.md#key-event--name--matches--data-) that SHIFT_TAB is a special key that is supported - however, my terminal does not seem to capture that command. Imaged below is what key-test.js shows when i hit 'shift+tab' in the terminal. Is powershell a terminal that simply does not support this?
![image](https://user-images.githubusercontent.com/11792324/128657722-f5e62ba5-68c1-41ee-bf27-9e595ad2263b.png)

detect-terminal-test.js results:
```
== OS and Environment Variables ==

Node version: v14.15.3
Terminal Kit version: 2.1.6
OS platform: win32
OS type: Windows_NT
OS release: 10.0.19041
OS version: Windows 10 Education
$TERM: (undefined)
$COLORTERM: (undefined)
$VTE_VERSION: (undefined)
$TERM_PROGRAM: (undefined)


== Using simple terminal guessing ==

.guessTerminal(): {"isTTY":true,"isSSH":false,"generic":"unknown"}
Terminal name: (undefined)
Terminal app ID: (undefined)
Generic terminal: unknown
Config file: xterm.generic.js

Support for delta escape sequence: OK
Support for 256 colors: NO
Support for true colors: NO
Support for cursor location request: OK (x: 38, y: 50)
Support for palette request: FAILED (Error: .getColor() timed out)
Issue #116 CURSOR_LOCATION keymap: OK
Issue #116 cursorLocation handler: OK


== Using advanced terminal detection ==

Can't get parent terminal info: Error [1]: Command failed: ps -h -o ppid -p 1992
'ps' is not recognized as an internal or external command,
operable program or batch file.

'ps' is not recognized as an internal or external command,
    at ChildProcess.exithandler (child_process.js:308:12)
    at ChildProcess.emit (events.js:315:20)
    at maybeClose (internal/child_process.js:1048:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:288:5)
Terminal name: (undefined)
Terminal app ID: (undefined)
Generic terminal: unknown
Config file: xterm.generic.js

Support for delta escape sequence: OK
Support for 256 colors: NO
Support for true colors: NO
Support for cursor location request: OK (x: 38, y: 50)
Support for palette request: FAILED (Error: .getColor() timed out)
Issue #116 CURSOR_LOCATION keymap: OK
Issue #116 cursorLocation handler: OK
```

PowerShell info:
```
PS C:\Users\Kevin's PC\Documents\terminal_chat> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      7.1.3
PSEdition                      Core
GitCommitId                    7.1.3
OS                             Microsoft Windows 10.0.19041
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by cronvel** [comment]
Hi,
Please run `sample/key-test.js` and hit *shift-tab*.
It will display how it is detected on your terminal.
Post a screenshot with the result.

**Comment by KevinLee3627** [comment]
![image](https://user-images.githubusercontent.com/11792324/128782615-b518ca3f-283f-4742-879a-1c09189e4bda.png)

**Comment by cronvel** [comment]
@KevinLee3627 Your terminal doesn't support *shift-tab*, sorry, there is nothing that could be done on the lib side.
